version: "3.7"
services:
  p-build:
      build: .
      container_name: "p-build"
      volumes:
          - type: volume
            source: public
            target: /www/app
      networks:
          - mynet

volumes:
    p-drum:
        external: true

networks:
    mynet:
        external: true
